title: ASiS docs
description: Documentatie produs ASiSerp
theme: just-the-docs
search_enabled: true
search.rel_url: false
favicon_ico: "/assets/favicon.ico"
logo: "/assets/logo.png"

url: https://docs.asis.ro

aux_links:
  Alfa Software: https://asw.ro

color_scheme: nil

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

  kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false